Save Format v3.0(19990112)
@begin Projects
 0 "1&mes_main01&mes_main01.pbl";
 1 "1&mes_z24&..\\Zaiko\\mes_z24.pbl";
@end;
appname "mes_main01";
applib "mes_main01.pbl";
LibList "mes_main01.pbl;..\\Zaiko\\mes_z01.pbl;..\\Zaiko\\mes_z02.pbl;..\\Zaiko\\mes_z03.pbl;..\\Zaiko\\mes_z05.pbl;..\\Zaiko\\mes_z06.pbl;..\\Zaiko\\mes_z07.pbl;..\\Zaiko\\mes_z09.pbl;..\\Zaiko\\mes_z10.pbl;..\\Zaiko\\mes_z11.pbl;..\\Zaiko\\mes_z12.pbl;..\\Zaiko\\mes_z13.pbl;..\\Zaiko\\mes_z14.pbl;..\\Zaiko\\mes_z15.pbl;..\\Zaiko\\mes_z16.pbl;..\\Zaiko\\mes_z17.pbl;..\\Zaiko\\mes_z18.pbl;..\\Zaiko\\mes_z19.pbl;..\\Zaiko\\mes_z20.pbl;..\\Zaiko\\mes_z21.pbl;..\\Zaiko\\mes_z22.pbl;..\\Zaiko\\mes_z23.pbl;..\\Zaiko\\mes_z24.pbl;..\\Zaiko\\mes_z25.pbl;..\\Zaiko\\mes_z30.pbl;..\\Zaiko\\mes_z31.pbl;..\\Zaiko\\mes_z32.pbl;..\\Zaiko\\mes_z33.pbl;..\\Zaiko\\mes_z35.pbl;..\\Zaiko\\mes_z36.pbl;..\\Zaiko\\mes_z99.pbl;..\\..\\..\\Com\\Src\\Pf\\com_pf.pbl;..\\..\\..\\Com\\Src\\Pf\\com_pf_api.pbl;..\\..\\..\\Com\\Src\\Pf\\com_pf_sup.pbl;..\\..\\..\\Com\\Src\\Pf\\pw_print.pbl;..\\..\\..\\Com\\Src\\Pu\\com_pu_object.pbl;..\\..\\..\\Com\\Src\\Pu\\mes_pu_tview.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_a_bunrui.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_bumon.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_event.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_group.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_gun.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_haifu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_help.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_higasi_bunrui.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_himoku.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_hin.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_hin_daigae.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_hinkubun.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_hinsitu_kanri.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_import.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kaiso_hin_kubun.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kamoku.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kansetu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kettei_tanka.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kinmu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_koutei.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_kouza_furikae.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_line.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_line_tanmatu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_lot_genpin_itf.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_opening.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_printer.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_prog.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_riyu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_siire.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_sisan.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_soufu.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_syohin.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_tani.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_tanto.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_team.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_tkubun.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_togo_line.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_torihiki.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_yosan_hin.pbl;..\\..\\..\\Com\\Src\\Pw\\com_pw_yusyo_tanka.pbl;..\\..\\..\\com\\src\\Genka\\com_g03.pbl;..\\Zaiko\\mes_z37.pbl";
type "pb";
